spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eb_prod
    username: eb_prod_user
    password: erudite
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false